all: factorytest.c
	/usr/local/Cavium_Networks/OCTEON-SDK-1.8.NEXG/tools/bin/mips64-octeon-linux-gnu-gcc -o factorytest factorytest.c
	cp factorytest ../

clean:
	rm -f factorytest
	rm -f ../factorytest
