FACTORY_DIR = ./factory
PHY_DIR = ./phy
REALTEK_DIR = ./realtek

all:
	cd $(FACTORY_DIR) && make
#	cd $(PHY_DIR) && make
#	cd $(REALTEK_DIR) && make

clean:
	cd $(FACTORY_DIR) && make clean
#	cd $(PHY_DIR) && make clean
#	cd $(REALTEK_DIR) && make clean

depend:
	cd $(FACTORY_DIR) && make depend
#	cd $(PHY_DIR) && make depend
#	cd $(REALTEK_DIR) && make depend
